name: Publish Docker image

on:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PERSONAL_ACCESS_TOKEN }}
      - name: Setup version
        id: setup_version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -r "s#refs/.+/##g")
          echo ::set-output name=version::$VERSION
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jamcha:latest
            ghcr.io/${{ github.repository_owner }}/jamcha:${{ steps.setup_version.outputs.version }}
